#!/bin/bash
#SBATCH -n 2
#SBATCH -c 6
mpiexec ./main_mpi_omp ./test_histogram.png
mpiexec ./main_mpi_omp ./test_histogram.png
mpiexec ./main_mpi_omp ./test_histogram.png
mpiexec ./main_mpi_omp ./test_histogram.png
mpiexec ./main_mpi_omp ./test_histogram.png
mpiexec ./main_mpi_omp ./test.png
mpiexec ./main_mpi_omp ./test.png
mpiexec ./main_mpi_omp ./test.png
mpiexec ./main_mpi_omp ./test.png
mpiexec ./main_mpi_omp ./test.png
mpiexec ./main_mpi_omp ./test_500.png
mpiexec ./main_mpi_omp ./test_500.png
mpiexec ./main_mpi_omp ./test_500.png
mpiexec ./main_mpi_omp ./test_500.png
mpiexec ./main_mpi_omp ./test_500.png
mpiexec ./main_mpi_omp ./test_1000.png
mpiexec ./main_mpi_omp ./test_1000.png
mpiexec ./main_mpi_omp ./test_1000.png
mpiexec ./main_mpi_omp ./test_1000.png
mpiexec ./main_mpi_omp ./test_1000.png
mpiexec ./main_mpi_omp ./test_10000.png
mpiexec ./main_mpi_omp ./test_10000.png
mpiexec ./main_mpi_omp ./test_10000.png
mpiexec ./main_mpi_omp ./test_10000.png
mpiexec ./main_mpi_omp ./test_10000.png
mpiexec ./main_mpi_omp ./median_test_1.png
mpiexec ./main_mpi_omp ./median_test_1.png
mpiexec ./main_mpi_omp ./median_test_1.png
mpiexec ./main_mpi_omp ./median_test_1.png
mpiexec ./main_mpi_omp ./median_test_1.png
mpiexec ./main_mpi_omp ./median_test_2.png
mpiexec ./main_mpi_omp ./median_test_2.png
mpiexec ./main_mpi_omp ./median_test_2.png
mpiexec ./main_mpi_omp ./median_test_2.png
mpiexec ./main_mpi_omp ./median_test_2.png
mpiexec ./main_mpi_omp ./lena.png
mpiexec ./main_mpi_omp ./lena.png
mpiexec ./main_mpi_omp ./lena.png
mpiexec ./main_mpi_omp ./lena.png
mpiexec ./main_mpi_omp ./lena.png