#!/usr/bin/bash
#SBATCH -n 2
#SBATCH -c 6
 ./main_seq ./test_histogram.png
 ./main_seq ./test_histogram.png
 ./main_seq ./test_histogram.png
 ./main_seq ./test_histogram.png
 ./main_seq ./test_histogram.png
 ./main_seq ./test.png
 ./main_seq ./test.png
 ./main_seq ./test.png
 ./main_seq ./test.png
 ./main_seq ./test.png
 ./main_seq ./test_500.png
 ./main_seq ./test_500.png
 ./main_seq ./test_500.png
 ./main_seq ./test_500.png
 ./main_seq ./test_500.png
 ./main_seq ./test_1000.png
 ./main_seq ./test_1000.png
 ./main_seq ./test_1000.png
 ./main_seq ./test_1000.png
 ./main_seq ./test_1000.png
 ./main_seq ./test_10000.png
 ./main_seq ./test_10000.png
 ./main_seq ./test_10000.png
 ./main_seq ./test_10000.png
 ./main_seq ./test_10000.png
 ./main_seq ./median_test_1.png
 ./main_seq ./median_test_1.png
 ./main_seq ./median_test_1.png
 ./main_seq ./median_test_1.png
 ./main_seq ./median_test_1.png
 ./main_seq ./median_test_2.png
 ./main_seq ./median_test_2.png
 ./main_seq ./median_test_2.png
 ./main_seq ./median_test_2.png
 ./main_seq ./median_test_2.png
 ./main_seq ./lena.png
 ./main_seq ./lena.png
 ./main_seq ./lena.png
 ./main_seq ./lena.png
 ./main_seq ./lena.png